package com.liferay.farmerPortlet.service.base;

import com.liferay.farmerPortlet.model.Region;
import com.liferay.farmerPortlet.service.RegionLocalService;
import com.liferay.farmerPortlet.service.persistence.FarmerPersistence;
import com.liferay.farmerPortlet.service.persistence.RegionPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the region local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.farmerPortlet.service.impl.RegionLocalServiceImpl}.
 * </p>
 *
 * @author Test Test
 * @see com.liferay.farmerPortlet.service.impl.RegionLocalServiceImpl
 * @see com.liferay.farmerPortlet.service.RegionLocalServiceUtil
 * @generated
 */
public abstract class RegionLocalServiceBaseImpl extends BaseLocalServiceImpl
    implements RegionLocalService, IdentifiableBean {
    @BeanReference(type = com.liferay.farmerPortlet.service.FarmerLocalService.class)
    protected com.liferay.farmerPortlet.service.FarmerLocalService farmerLocalService;
    @BeanReference(type = com.liferay.farmerPortlet.service.FarmerService.class)
    protected com.liferay.farmerPortlet.service.FarmerService farmerService;
    @BeanReference(type = FarmerPersistence.class)
    protected FarmerPersistence farmerPersistence;
    @BeanReference(type = com.liferay.farmerPortlet.service.RegionLocalService.class)
    protected com.liferay.farmerPortlet.service.RegionLocalService regionLocalService;
    @BeanReference(type = com.liferay.farmerPortlet.service.RegionService.class)
    protected com.liferay.farmerPortlet.service.RegionService regionService;
    @BeanReference(type = RegionPersistence.class)
    protected RegionPersistence regionPersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private RegionLocalServiceClpInvoker _clpInvoker = new RegionLocalServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.liferay.farmerPortlet.service.RegionLocalServiceUtil} to access the region local service.
     */

    /**
     * Adds the region to the database. Also notifies the appropriate model listeners.
     *
     * @param region the region
     * @return the region that was added
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    @Override
    public Region addRegion(Region region) throws SystemException {
        region.setNew(true);

        return regionPersistence.update(region);
    }

    /**
     * Creates a new region with the primary key. Does not add the region to the database.
     *
     * @param regionId the primary key for the new region
     * @return the new region
     */
    @Override
    public Region createRegion(long regionId) {
        return regionPersistence.create(regionId);
    }

    /**
     * Deletes the region with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param regionId the primary key of the region
     * @return the region that was removed
     * @throws PortalException if a region with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    @Override
    public Region deleteRegion(long regionId)
        throws PortalException, SystemException {
        return regionPersistence.remove(regionId);
    }

    /**
     * Deletes the region from the database. Also notifies the appropriate model listeners.
     *
     * @param region the region
     * @return the region that was removed
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    @Override
    public Region deleteRegion(Region region) throws SystemException {
        return regionPersistence.remove(region);
    }

    @Override
    public DynamicQuery dynamicQuery() {
        Class<?> clazz = getClass();

        return DynamicQueryFactoryUtil.forClass(Region.class,
            clazz.getClassLoader());
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return regionPersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.farmerPortlet.model.impl.RegionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return regionPersistence.findWithDynamicQuery(dynamicQuery, start, end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.farmerPortlet.model.impl.RegionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return regionPersistence.findWithDynamicQuery(dynamicQuery, start, end,
            orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    @Override
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return regionPersistence.countWithDynamicQuery(dynamicQuery);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @param projection the projection to apply to the query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    @Override
    public long dynamicQueryCount(DynamicQuery dynamicQuery,
        Projection projection) throws SystemException {
        return regionPersistence.countWithDynamicQuery(dynamicQuery, projection);
    }

    @Override
    public Region fetchRegion(long regionId) throws SystemException {
        return regionPersistence.fetchByPrimaryKey(regionId);
    }

    /**
     * Returns the region with the primary key.
     *
     * @param regionId the primary key of the region
     * @return the region
     * @throws PortalException if a region with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Override
    public Region getRegion(long regionId)
        throws PortalException, SystemException {
        return regionPersistence.findByPrimaryKey(regionId);
    }

    @Override
    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return regionPersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns a range of all the regions.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.farmerPortlet.model.impl.RegionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param start the lower bound of the range of regions
     * @param end the upper bound of the range of regions (not inclusive)
     * @return the range of regions
     * @throws SystemException if a system exception occurred
     */
    @Override
    public List<Region> getRegions(int start, int end)
        throws SystemException {
        return regionPersistence.findAll(start, end);
    }

    /**
     * Returns the number of regions.
     *
     * @return the number of regions
     * @throws SystemException if a system exception occurred
     */
    @Override
    public int getRegionsCount() throws SystemException {
        return regionPersistence.countAll();
    }

    /**
     * Updates the region in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param region the region
     * @return the region that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    @Override
    public Region updateRegion(Region region) throws SystemException {
        return regionPersistence.update(region);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public void addFarmerRegion(long farmerId, long regionId)
        throws SystemException {
        farmerPersistence.addRegion(farmerId, regionId);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public void addFarmerRegion(long farmerId, Region region)
        throws SystemException {
        farmerPersistence.addRegion(farmerId, region);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public void addFarmerRegions(long farmerId, long[] regionIds)
        throws SystemException {
        farmerPersistence.addRegions(farmerId, regionIds);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public void addFarmerRegions(long farmerId, List<Region> Regions)
        throws SystemException {
        farmerPersistence.addRegions(farmerId, Regions);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public void clearFarmerRegions(long farmerId) throws SystemException {
        farmerPersistence.clearRegions(farmerId);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public void deleteFarmerRegion(long farmerId, long regionId)
        throws SystemException {
        farmerPersistence.removeRegion(farmerId, regionId);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public void deleteFarmerRegion(long farmerId, Region region)
        throws SystemException {
        farmerPersistence.removeRegion(farmerId, region);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public void deleteFarmerRegions(long farmerId, long[] regionIds)
        throws SystemException {
        farmerPersistence.removeRegions(farmerId, regionIds);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public void deleteFarmerRegions(long farmerId, List<Region> Regions)
        throws SystemException {
        farmerPersistence.removeRegions(farmerId, Regions);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public List<Region> getFarmerRegions(long farmerId)
        throws SystemException {
        return farmerPersistence.getRegions(farmerId);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public List<Region> getFarmerRegions(long farmerId, int start, int end)
        throws SystemException {
        return farmerPersistence.getRegions(farmerId, start, end);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public List<Region> getFarmerRegions(long farmerId, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return farmerPersistence.getRegions(farmerId, start, end,
            orderByComparator);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public int getFarmerRegionsCount(long farmerId) throws SystemException {
        return farmerPersistence.getRegionsSize(farmerId);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public boolean hasFarmerRegion(long farmerId, long regionId)
        throws SystemException {
        return farmerPersistence.containsRegion(farmerId, regionId);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public boolean hasFarmerRegions(long farmerId) throws SystemException {
        return farmerPersistence.containsRegions(farmerId);
    }

    /**
     * @throws SystemException if a system exception occurred
     */
    @Override
    public void setFarmerRegions(long farmerId, long[] regionIds)
        throws SystemException {
        farmerPersistence.setRegions(farmerId, regionIds);
    }

    /**
     * Returns the farmer local service.
     *
     * @return the farmer local service
     */
    public com.liferay.farmerPortlet.service.FarmerLocalService getFarmerLocalService() {
        return farmerLocalService;
    }

    /**
     * Sets the farmer local service.
     *
     * @param farmerLocalService the farmer local service
     */
    public void setFarmerLocalService(
        com.liferay.farmerPortlet.service.FarmerLocalService farmerLocalService) {
        this.farmerLocalService = farmerLocalService;
    }

    /**
     * Returns the farmer remote service.
     *
     * @return the farmer remote service
     */
    public com.liferay.farmerPortlet.service.FarmerService getFarmerService() {
        return farmerService;
    }

    /**
     * Sets the farmer remote service.
     *
     * @param farmerService the farmer remote service
     */
    public void setFarmerService(
        com.liferay.farmerPortlet.service.FarmerService farmerService) {
        this.farmerService = farmerService;
    }

    /**
     * Returns the farmer persistence.
     *
     * @return the farmer persistence
     */
    public FarmerPersistence getFarmerPersistence() {
        return farmerPersistence;
    }

    /**
     * Sets the farmer persistence.
     *
     * @param farmerPersistence the farmer persistence
     */
    public void setFarmerPersistence(FarmerPersistence farmerPersistence) {
        this.farmerPersistence = farmerPersistence;
    }

    /**
     * Returns the region local service.
     *
     * @return the region local service
     */
    public com.liferay.farmerPortlet.service.RegionLocalService getRegionLocalService() {
        return regionLocalService;
    }

    /**
     * Sets the region local service.
     *
     * @param regionLocalService the region local service
     */
    public void setRegionLocalService(
        com.liferay.farmerPortlet.service.RegionLocalService regionLocalService) {
        this.regionLocalService = regionLocalService;
    }

    /**
     * Returns the region remote service.
     *
     * @return the region remote service
     */
    public com.liferay.farmerPortlet.service.RegionService getRegionService() {
        return regionService;
    }

    /**
     * Sets the region remote service.
     *
     * @param regionService the region remote service
     */
    public void setRegionService(
        com.liferay.farmerPortlet.service.RegionService regionService) {
        this.regionService = regionService;
    }

    /**
     * Returns the region persistence.
     *
     * @return the region persistence
     */
    public RegionPersistence getRegionPersistence() {
        return regionPersistence;
    }

    /**
     * Sets the region persistence.
     *
     * @param regionPersistence the region persistence
     */
    public void setRegionPersistence(RegionPersistence regionPersistence) {
        this.regionPersistence = regionPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();

        PersistedModelLocalServiceRegistryUtil.register("com.liferay.farmerPortlet.model.Region",
            regionLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "com.liferay.farmerPortlet.model.Region");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Region.class;
    }

    protected String getModelClassName() {
        return Region.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = regionPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
