package com.liferay.farmerPortlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Region service. Represents a row in the &quot;TestTask_Region&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.farmerPortlet.model.impl.RegionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.farmerPortlet.model.impl.RegionImpl}.
 * </p>
 *
 * @author Test Test
 * @see Region
 * @see com.liferay.farmerPortlet.model.impl.RegionImpl
 * @see com.liferay.farmerPortlet.model.impl.RegionModelImpl
 * @generated
 */
public interface RegionModel extends BaseModel<Region> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a region model instance should use the {@link Region} interface instead.
     */

    /**
     * Returns the primary key of this region.
     *
     * @return the primary key of this region
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this region.
     *
     * @param primaryKey the primary key of this region
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the region ID of this region.
     *
     * @return the region ID of this region
     */
    public long getRegionId();

    /**
     * Sets the region ID of this region.
     *
     * @param regionId the region ID of this region
     */
    public void setRegionId(long regionId);

    /**
     * Returns the region name of this region.
     *
     * @return the region name of this region
     */
    @AutoEscape
    public String getRegionName();

    /**
     * Sets the region name of this region.
     *
     * @param regionName the region name of this region
     */
    public void setRegionName(String regionName);

    /**
     * Returns the region code of this region.
     *
     * @return the region code of this region
     */
    @AutoEscape
    public String getRegionCode();

    /**
     * Sets the region code of this region.
     *
     * @param regionCode the region code of this region
     */
    public void setRegionCode(String regionCode);

    /**
     * Returns the archive status of this region.
     *
     * @return the archive status of this region
     */
    @AutoEscape
    public String getArchiveStatus();

    /**
     * Sets the archive status of this region.
     *
     * @param archiveStatus the archive status of this region
     */
    public void setArchiveStatus(String archiveStatus);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.liferay.farmerPortlet.model.Region region);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.farmerPortlet.model.Region> toCacheModel();

    @Override
    public com.liferay.farmerPortlet.model.Region toEscapedModel();

    @Override
    public com.liferay.farmerPortlet.model.Region toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
